py-libhdate/py-libhdate

DEVELOPMENT.rst
setup.cfg
setup.py
src/hdate/zmanim.py

Also add some documentation on how to develop for this library

Add support for adding providing timezone as a datetime object

---

hdate/common.py
hdate/date.py
hdate/htables.py
hdate/zmanim.py
tests/test_hdate.py

Adds some helpful properties such as next_day, previous_day, is_holiday as well as notable functions like get_upcoming_shabbat_hdate() and get_next_yom_tov().
Also refactors some of the holiday list identification logic into something reusable by _holiday_entry() and the new code.

Add functions for identifying upcoming shabbat and Yom Tov

---

hdate/zmanim.py

Rewrite the function in terms of havdala and candle lighting time.
This fixes #39 
This might fix
-  home-assistant/home-assistant#23032
-  home-assistant/home-assistant#24479
-  home-assistant/home-assistant#23852
Thanks to @zalke for pointing out the fix

 Rewrite issur_melacha_in_effect 

---

.github/pull_request_template.md
.github/workflows/run-tests.yaml
setup.py

fix: Minor typos - test changelog generation

---

.github/workflows/auto-versioning.yaml

Use regex match for label name

---

.github/workflows/auto-versioning.yaml

Fix: Use specific deploy label

---

.github/workflows/auto-versioning.yaml

Use repo-sync instead of peter evans create pull request action

---

.github/workflows/auto-versioning.yaml

Use checkout v1 as v2 is broken with creation of PR

---

.github/workflows/run-tests.yaml

fix: Allow user to trigger tests on their forked branch as well

---

.github/workflows/auto-release.yaml

chore: Add auto-release workflow action

---

setup.cfg
setup.py

Bump version: 0.9.7 → 0.9.8

---

.github/workflows/release.yaml

Fix missing closing quote

---

DEVELOPMENT.rst

Fix instructions for setting up development environment

---

.readthedocs.yaml

Add support for readthedocs
Fixes: #<issue number>

Setup read the docs configuration

---

.github/workflows/release.yaml
pyproject.toml

Fix version in pyproject.toml and fix github release flow

---

poetry.lock
pyproject.toml

Fix pytz version requirement

---

hdate/zmanim.py
tests/test_hdate.py
tests/test_zmanim.py

Consistently name Shabbat or chag

---

.pre-commit-config.yaml
hdate/zmanim.py

Fix motzei shabbat

---

hdate/common.py

Use a Dataclass for HebrewDate class

Use dataclass for HebrewDate

---

hdate/zmanim.py

This will avoid calling the dict() function

Use dict literal

---

tox.ini

add Python 3.11 testing to tox and remove 3.7

---

.gitignore
hdate/date.py
hdate/htables.py
tests/test_hdate.py

This PR is adding a new method - is leap year
Fixes: #119

add Is leap year method

---

.github/workflows/release.yaml
CHANGELOG.md

Fix changelog not updating and commit not being pushed in release flow

---

.github/workflows/run-tests.yaml
hdate/location.py
hdate/zmanim.py
pdm.lock
pyproject.toml
tox.ini

Deprecate support for Python 3.8, add support for Python 3.13

---

.github/release-drafter.yaml
.gitignore
.pre-commit-config.yaml
docs/source/conf.py
hdate/converters.py
hdate/date.py
hdate/hebrew_date.py
hdate/htables.py
hdate/location.py
hdate/zmanim.py
pdm.lock
pyproject.toml
tests/conftest.py
tests/test_converters.py
tests/test_hdate.py
tests/test_hdate_api.py
tests/test_hdate_string.py
tests/test_zmanim.py

Make libhdate fully typed

---

hdate/date.py
hdate/htables.py
tests/test_hdate.py

This should solve is_holiday behavior
Fixes: #137

Fix is_holiday behavior

---

hdate/htables.py

Adds a helper method because now one of our options is both Chanukah and Rosh Chodesh
Fixes: #<issue number>

Add helper method for all holiday options

---

hdate/location.py

Remove unneeded Location __repr__

---

hdate/zmanim.py
tests/test_hdate_api.py
tests/test_zmanim.py

Zmanim should be calculated based on today's Gregorian date. The time part should only be taken into consideration when trying to compare a given time to a calculated zman.
As such, in cases where we need the current time, we ask for it explicitly. 
Fixes: #<issue number>

Improve Zmanim API

---

hdate/omer.py
tests/__snapshots__/test_omer.ambr

In the italian Nusach the is verb comes at the end of the prefix.
Fixes: #<issue number>

Fix Italian Omer Nusach

---

.github/workflows/run-tests.yaml
tox.ini

Add support for uploading to codecov

---

.github/workflows/run-tests.yaml
.gitignore
pdm.lock
pyproject.toml
tests/test_zmanim.py
tox.ini

Make astral a real optional dependency
